name: Deploy Infrastructure and Run FastAPI App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_infra:
    name: Deploy Infrastructure with Terragrunt
    runs-on: ubuntu-latest
    outputs:
      S3_BUCKET_NAME: ${{ steps.output_values.outputs.S3_BUCKET_NAME }}
      CLOUDFRONT_URL: ${{ steps.output_values.outputs.CLOUDFRONT_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Format Terraform Code
      run: terraform fmt -check
      working-directory: ./terragrunt-terraform

    - name: Install Terragrunt
      run: |
        wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.35.16/terragrunt_linux_amd64
        chmod +x terragrunt
        sudo mv terragrunt /usr/local/bin/

    - name: Terragrunt Apply
      run: | 
        cd terragrunt-terraform/live/prod
        terragrunt run-all apply --terragrunt-non-interactive


    # Save CloudFront URL and S3 bucket name for later steps
    - name: Set output values
      id: output_values
      run: |
        cd terragrunt-terraform/live/prod/cloudfront   
        echo "CLOUDFRONT_URL=$(terragrunt output -raw cloudfront_url)" >> $GITHUB_OUTPUT
        cd ../s3
        echo "S3_BUCKET_NAME=$(terragrunt output -raw bucket_name)" >> $GITHUB_OUTPUT

  run_fastapi_app:
    name: Run FastAPI App Steps
    runs-on: ubuntu-latest
    needs: deploy_infra

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./python/app

    - name: Start FastAPI Server and trigger endpoints
      env:
        CLOUDFRONT_URL: ${{ needs.deploy_infra.outputs.CLOUDFRONT_URL }}
        S3_BUCKET_NAME: ${{ needs.deploy_infra.outputs.S3_BUCKET_NAME }}
      run: |
        export "CLOUDFRONT_URL=https://$CLOUDFRONT_URL"
        uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 10
        curl -s http://localhost:8000/products
        response=$(curl -s http://localhost:8000/verify)
        echo $response
      working-directory: ./python/app

